package com.google.android.mail.common.html.parser;

import com.google.common.collect.*;
import java.util.*;

public final class b
{
    private static final HashMap<String, HTML$Element> cpW;
    private static final HashMap<String, a> cpX;
    private static final x cpY;
    public static final HTML$Element cpZ;
    public static final HTML$Element cqA;
    public static final HTML$Element cqB;
    public static final HTML$Element cqC;
    public static final HTML$Element cqD;
    public static final HTML$Element cqE;
    public static final HTML$Element cqF;
    public static final HTML$Element cqG;
    public static final HTML$Element cqH;
    public static final HTML$Element cqI;
    public static final HTML$Element cqJ;
    public static final HTML$Element cqK;
    public static final HTML$Element cqL;
    public static final HTML$Element cqM;
    public static final HTML$Element cqN;
    public static final HTML$Element cqO;
    public static final HTML$Element cqP;
    public static final HTML$Element cqQ;
    public static final HTML$Element cqR;
    public static final HTML$Element cqS;
    public static final HTML$Element cqT;
    public static final HTML$Element cqU;
    public static final HTML$Element cqV;
    public static final HTML$Element cqW;
    public static final HTML$Element cqX;
    public static final HTML$Element cqY;
    public static final HTML$Element cqZ;
    public static final HTML$Element cqa;
    public static final HTML$Element cqb;
    public static final HTML$Element cqc;
    public static final HTML$Element cqd;
    public static final HTML$Element cqe;
    public static final HTML$Element cqf;
    public static final HTML$Element cqg;
    public static final HTML$Element cqh;
    public static final HTML$Element cqi;
    public static final HTML$Element cqj;
    public static final HTML$Element cqk;
    public static final HTML$Element cql;
    public static final HTML$Element cqm;
    public static final HTML$Element cqn;
    public static final HTML$Element cqo;
    public static final HTML$Element cqp;
    public static final HTML$Element cqq;
    public static final HTML$Element cqr;
    public static final HTML$Element cqs;
    public static final HTML$Element cqt;
    public static final HTML$Element cqu;
    public static final HTML$Element cqv;
    public static final HTML$Element cqw;
    public static final HTML$Element cqx;
    public static final HTML$Element cqy;
    public static final HTML$Element cqz;
    public static final HTML$Element crA;
    public static final HTML$Element crB;
    public static final HTML$Element crC;
    public static final HTML$Element crD;
    public static final HTML$Element crE;
    public static final HTML$Element crF;
    public static final HTML$Element crG;
    public static final HTML$Element crH;
    public static final HTML$Element crI;
    public static final HTML$Element crJ;
    public static final HTML$Element crK;
    public static final HTML$Element crL;
    public static final a crM;
    public static final a crN;
    public static final a crO;
    public static final a crP;
    public static final a crQ;
    public static final a crR;
    public static final a crS;
    public static final a crT;
    public static final a crU;
    public static final a crV;
    public static final a crW;
    public static final a crX;
    public static final a crY;
    public static final a crZ;
    public static final HTML$Element cra;
    public static final HTML$Element crb;
    public static final HTML$Element crc;
    public static final HTML$Element crd;
    public static final HTML$Element cre;
    public static final HTML$Element crf;
    public static final HTML$Element crg;
    public static final HTML$Element crh;
    public static final HTML$Element cri;
    public static final HTML$Element crj;
    public static final HTML$Element crk;
    public static final HTML$Element crl;
    public static final HTML$Element crm;
    public static final HTML$Element crn;
    public static final HTML$Element cro;
    public static final HTML$Element crp;
    public static final HTML$Element crq;
    public static final HTML$Element crr;
    public static final HTML$Element crs;
    public static final HTML$Element crt;
    public static final HTML$Element cru;
    public static final HTML$Element crv;
    public static final HTML$Element crw;
    public static final HTML$Element crx;
    public static final HTML$Element cry;
    public static final HTML$Element crz;
    public static final a csA;
    public static final a csB;
    public static final a csC;
    public static final a csD;
    public static final a csE;
    public static final a csF;
    public static final a csG;
    public static final a csH;
    public static final a csI;
    public static final a csJ;
    public static final a csK;
    public static final a csL;
    public static final a csM;
    public static final a csN;
    public static final a csO;
    public static final a csP;
    public static final a csQ;
    public static final a csR;
    public static final a csS;
    public static final a csT;
    public static final a csU;
    public static final a csV;
    public static final a csW;
    public static final a csX;
    public static final a csY;
    public static final a csZ;
    public static final a csa;
    public static final a csb;
    public static final a csc;
    public static final a csd;
    public static final a cse;
    public static final a csf;
    public static final a csg;
    public static final a csh;
    public static final a csi;
    public static final a csj;
    public static final a csk;
    public static final a csl;
    public static final a csm;
    public static final a csn;
    public static final a cso;
    public static final a csp;
    public static final a csq;
    public static final a csr;
    public static final a css;
    public static final a cst;
    public static final a csu;
    public static final a csv;
    public static final a csw;
    public static final a csx;
    public static final a csy;
    public static final a csz;
    public static final a ctA;
    public static final a ctB;
    public static final a ctC;
    public static final a ctD;
    public static final a ctE;
    public static final a ctF;
    public static final a ctG;
    public static final a ctH;
    public static final a ctI;
    public static final a ctJ;
    public static final a ctK;
    public static final a ctL;
    public static final a ctM;
    public static final a ctN;
    public static final a ctO;
    public static final a ctP;
    public static final a ctQ;
    public static final a ctR;
    public static final a ctS;
    public static final a ctT;
    public static final a ctU;
    public static final a ctV;
    public static final a ctW;
    public static final a ctX;
    public static final a ctY;
    public static final a ctZ;
    public static final a cta;
    public static final a ctb;
    public static final a ctc;
    public static final a ctd;
    public static final a cte;
    public static final a ctf;
    public static final a ctg;
    public static final a cth;
    public static final a cti;
    public static final a ctj;
    public static final a ctk;
    public static final a ctl;
    public static final a ctm;
    public static final a ctn;
    public static final a cto;
    public static final a ctp;
    public static final a ctq;
    public static final a ctr;
    public static final a cts;
    public static final a ctt;
    public static final a ctu;
    public static final a ctv;
    public static final a ctw;
    public static final a ctx;
    public static final a cty;
    public static final a ctz;
    public static final a cua;
    
    static {
        cpW = Maps.aan();
        cpX = Maps.aan();
        cpY = new c();
        cpZ = a("A", "", HTML$Element$Flow.cpS, 0);
        cqa = a("ABBR", "", HTML$Element$Flow.cpS, 0);
        cqb = a("ACRONYM", "", HTML$Element$Flow.cpS, 0);
        cqc = a("ADDRESS", "", HTML$Element$Flow.cpT, 0);
        cqd = at("APPLET", "");
        cqe = at("AREA", "E");
        cqf = a("B", "", HTML$Element$Flow.cpS, 0);
        cqg = at("BASE", "E");
        cqh = at("BASEFONT", "E");
        cqi = a("BDO", "", HTML$Element$Flow.cpS, 0);
        cqj = a("BIG", "", HTML$Element$Flow.cpS, 0);
        cqk = a("BLOCKQUOTE", "B", HTML$Element$Flow.cpT, 0);
        cql = at("BODY", "O");
        cqm = a("BR", "EB", HTML$Element$Flow.cpS, 0);
        cqn = a("BUTTON", "", HTML$Element$Flow.cpS, 0);
        cqo = a("CAPTION", "", HTML$Element$Flow.cpU, 1);
        cqp = a("CENTER", "B", HTML$Element$Flow.cpT, 0);
        cqq = a("CITE", "", HTML$Element$Flow.cpS, 0);
        cqr = a("CODE", "", HTML$Element$Flow.cpS, 0);
        cqs = a("COL", "E", HTML$Element$Flow.cpU, 1);
        cqt = a("COLGROUP", "O", HTML$Element$Flow.cpU, 1);
        cqu = at("DD", "OB");
        cqv = at("DEL", "");
        cqw = a("DFN", "", HTML$Element$Flow.cpS, 0);
        cqx = a("DIR", "B", HTML$Element$Flow.cpT, 0);
        cqy = a("DIV", "B", HTML$Element$Flow.cpT, 0);
        cqz = a("DL", "B", HTML$Element$Flow.cpT, 0);
        cqA = at("DT", "OB");
        cqB = a("EM", "", HTML$Element$Flow.cpS, 0);
        cqC = a("FIELDSET", "", HTML$Element$Flow.cpT, 0);
        cqD = a("FONT", "", HTML$Element$Flow.cpS, 0);
        cqE = a("FORM", "B", HTML$Element$Flow.cpT, 0);
        cqF = at("FRAME", "E");
        cqG = at("FRAMESET", "");
        cqH = a("H1", "B", HTML$Element$Flow.cpT, 0);
        cqI = a("H2", "B", HTML$Element$Flow.cpT, 0);
        cqJ = a("H3", "B", HTML$Element$Flow.cpT, 0);
        cqK = a("H4", "B", HTML$Element$Flow.cpT, 0);
        cqL = a("H5", "B", HTML$Element$Flow.cpT, 0);
        cqM = a("H6", "B", HTML$Element$Flow.cpT, 0);
        cqN = at("HEAD", "OB");
        cqO = a("HR", "EB", HTML$Element$Flow.cpT, 0);
        cqP = at("HTML", "OB");
        cqQ = a("I", "", HTML$Element$Flow.cpS, 0);
        cqR = at("IFRAME", "");
        cqS = a("IMG", "E", HTML$Element$Flow.cpS, 0);
        cqT = a("INPUT", "E", HTML$Element$Flow.cpS, 0);
        cqU = at("INS", "");
        cqV = at("ISINDEX", "EB");
        cqW = a("KBD", "", HTML$Element$Flow.cpS, 0);
        cqX = a("LABEL", "", HTML$Element$Flow.cpS, 0);
        cqY = at("LEGEND", "");
        cqZ = at("LI", "OB");
        cra = at("LINK", "E");
        crb = a("MAP", "", HTML$Element$Flow.cpS, 0);
        crc = a("MENU", "B", HTML$Element$Flow.cpT, 0);
        crd = at("META", "E");
        cre = at("NOFRAMES", "B");
        crf = a("NOSCRIPT", "", HTML$Element$Flow.cpT, 0);
        crg = a("OBJECT", "", HTML$Element$Flow.cpS, 0);
        crh = a("OL", "B", HTML$Element$Flow.cpT, 0);
        cri = at("OPTGROUP", "");
        crj = at("OPTION", "O");
        crk = a("P", "OB", HTML$Element$Flow.cpT, 0);
        crl = at("PARAM", "E");
        crm = a("PRE", "B", HTML$Element$Flow.cpT, 0);
        crn = a("Q", "", HTML$Element$Flow.cpS, 0);
        cro = a("S", "", HTML$Element$Flow.cpS, 0);
        crp = a("SAMP", "", HTML$Element$Flow.cpS, 0);
        crq = a("SCRIPT", "", HTML$Element$Flow.cpS, 0);
        crr = a("SELECT", "", HTML$Element$Flow.cpS, 0);
        crs = a("SMALL", "", HTML$Element$Flow.cpS, 0);
        crt = a("SPAN", "", HTML$Element$Flow.cpS, 0);
        cru = a("STRIKE", "", HTML$Element$Flow.cpS, 0);
        crv = a("STRONG", "", HTML$Element$Flow.cpS, 0);
        crw = at("STYLE", "");
        crx = a("SUB", "", HTML$Element$Flow.cpS, 0);
        cry = a("SUP", "", HTML$Element$Flow.cpS, 0);
        crz = a("TABLE", "B", HTML$Element$Flow.cpT, 1);
        crA = a("TBODY", "O", HTML$Element$Flow.cpU, 1);
        crB = a("TD", "OB", HTML$Element$Flow.cpU, 1);
        crC = a("TEXTAREA", "", HTML$Element$Flow.cpS, 0);
        crD = a("TFOOT", "O", HTML$Element$Flow.cpU, 1);
        crE = a("TH", "OB", HTML$Element$Flow.cpU, 1);
        crF = a("THEAD", "O", HTML$Element$Flow.cpU, 1);
        crG = at("TITLE", "B");
        crH = a("TR", "OB", HTML$Element$Flow.cpU, 1);
        crI = a("TT", "", HTML$Element$Flow.cpS, 0);
        crJ = a("U", "", HTML$Element$Flow.cpS, 0);
        crK = a("UL", "B", HTML$Element$Flow.cpT, 0);
        crL = a("VAR", "", HTML$Element$Flow.cpS, 0);
        crM = a("ABBR", 0, null);
        crN = a("ACCEPT", 0, null);
        crO = a("ACCEPT-CHARSET", 0, null);
        crP = a("ACCESSKEY", 0, null);
        crQ = a("ACTION", 1, null);
        crR = a("ALIGN", 3, new String[] { "left", "center", "right", "justify", "char", "top", "bottom", "middle" });
        crS = a("ALINK", 0, null);
        crT = a("ALT", 0, null);
        crU = a("ARCHIVE", 1, null);
        crV = a("AXIS", 0, null);
        crW = a("BACKGROUND", 1, null);
        crX = a("BGCOLOR", 0, null);
        crY = a("BORDER", 0, null);
        crZ = a("CELLPADDING", 0, null);
        csa = a("CELLSPACING", 0, null);
        csb = a("CHAR", 0, null);
        csc = a("CHAROFF", 0, null);
        csd = a("CHARSET", 0, null);
        cse = a("CHECKED", 4, null);
        csf = a("CITE", 1, null);
        csg = a("CLASS", 0, null);
        csh = a("CLASSID", 1, null);
        csi = a("CLEAR", 3, new String[] { "left", "all", "right", "none" });
        csj = a("CODE", 0, null);
        csk = a("CODEBASE", 1, null);
        csl = a("CODETYPE", 0, null);
        csm = a("COLOR", 0, null);
        csn = a("COLS", 0, null);
        cso = a("COLSPAN", 0, null);
        csp = a("COMPACT", 4, null);
        csq = a("CONTENT", 0, null);
        csr = a("COORDS", 0, null);
        css = a("DATA", 1, null);
        cst = a("DATETIME", 0, null);
        csu = a("DECLARE", 4, null);
        csv = a("DEFER", 4, null);
        csw = a("DIR", 3, new String[] { "ltr", "rtl" });
        csx = a("DISABLED", 4, null);
        csy = a("ENCTYPE", 0, null);
        csz = a("FACE", 0, null);
        csA = a("FOR", 0, null);
        csB = a("FRAME", 0, null);
        csC = a("FRAMEBORDER", 3, new String[] { "1", "0" });
        csD = a("HEADERS", 0, null);
        csE = a("HEIGHT", 0, null);
        csF = a("HREF", 1, null);
        csG = a("HREFLANG", 0, null);
        csH = a("HSPACE", 0, null);
        csI = a("HTTP-EQUIV", 0, null);
        csJ = a("ID", 0, null);
        csK = a("ISMAP", 4, null);
        csL = a("LABEL", 0, null);
        csM = a("LANG", 0, null);
        csN = a("LANGUAGE", 0, null);
        csO = a("LINK", 0, null);
        csP = a("LONGDESC", 1, null);
        csQ = a("MARGINHEIGHT", 0, null);
        csR = a("MARGINWIDTH", 0, null);
        csS = a("MAXLENGTH", 0, null);
        csT = a("MEDIA", 0, null);
        csU = a("METHOD", 3, new String[] { "get", "post" });
        csV = a("MULTIPLE", 4, null);
        csW = a("NAME", 0, null);
        csX = a("NOHREF", 4, null);
        csY = a("NORESIZE", 4, null);
        csZ = a("NOSHADE", 4, null);
        cta = a("NOWRAP", 4, null);
        ctb = a("OBJECT", 0, null);
        ctc = a("ONBLUR", 2, null);
        ctd = a("ONCHANGE", 2, null);
        cte = a("ONCLICK", 2, null);
        ctf = a("ONDBLCLICK", 2, null);
        ctg = a("ONFOCUS", 2, null);
        cth = a("ONKEYDOWN", 2, null);
        cti = a("ONKEYPRESS", 2, null);
        ctj = a("ONKEYUP", 2, null);
        ctk = a("ONLOAD", 2, null);
        ctl = a("ONMOUSEDOWN", 2, null);
        ctm = a("ONMOUSEMOVE", 2, null);
        ctn = a("ONMOUSEOUT", 2, null);
        cto = a("ONMOUSEOVER", 2, null);
        ctp = a("ONMOUSEUP", 2, null);
        ctq = a("ONRESET", 2, null);
        ctr = a("ONSELECT", 2, null);
        cts = a("ONSUBMIT", 2, null);
        ctt = a("ONUNLOAD", 2, null);
        ctu = a("PROFILE", 1, null);
        ctv = a("PROMPT", 0, null);
        ctw = a("READONLY", 4, null);
        ctx = a("REL", 0, null);
        cty = a("REV", 0, null);
        ctz = a("ROWS", 0, null);
        ctA = a("ROWSPAN", 0, null);
        ctB = a("RULES", 0, null);
        ctC = a("SCHEME", 0, null);
        ctD = a("SCOPE", 0, null);
        ctE = a("SCROLLING", 3, new String[] { "yes", "no", "auto" });
        ctF = a("SELECTED", 4, null);
        ctG = a("SHAPE", 0, null);
        ctH = a("SIZE", 0, null);
        ctI = a("SPAN", 0, null);
        ctJ = a("SRC", 1, null);
        ctK = a("STANDBY", 0, null);
        ctL = a("START", 0, null);
        ctM = a("STYLE", 0, null);
        ctN = a("SUMMARY", 0, null);
        ctO = a("TABINDEX", 0, null);
        ctP = a("TARGET", 0, null);
        ctQ = a("TEXT", 0, null);
        ctR = a("TITLE", 0, null);
        ctS = a("TYPE", 0, null);
        ctT = a("USEMAP", 1, null);
        ctU = a("VALIGN", 3, new String[] { "top", "middle", "bottom", "baseline" });
        ctV = a("VALUE", 0, null);
        ctW = a("VALUETYPE", 3, new String[] { "data", "ref", "object" });
        ctX = a("VERSION", 0, null);
        ctY = a("VLINK", 0, null);
        ctZ = a("VSPACE", 0, null);
        cua = a("WIDTH", 0, null);
    }
    
    public static x Wd() {
        return b.cpY;
    }
    
    private static HTML$Element a(final String s, final String s2, final HTML$Element$Flow html$Element$Flow, final int n) {
        int i = 0;
        final String lowerCase = s.toLowerCase();
        boolean b = false;
        boolean b2 = false;
        boolean b3 = false;
        while (i < s2.length()) {
            switch (s2.charAt(i)) {
                default: {
                    throw new Error("Unknown element flag");
                }
                case 'E': {
                    b3 = true;
                    break;
                }
                case 'O': {
                    b2 = true;
                    break;
                }
                case 'B': {
                    b = true;
                    break;
                }
            }
            ++i;
        }
        final HTML$Element html$Element = new HTML$Element(lowerCase, n, b3, b2, b, html$Element$Flow);
        com.google.android.mail.common.html.parser.b.cpW.put(lowerCase, html$Element);
        return html$Element;
    }
    
    private static a a(final String s, final int n, final String[] array) {
        final String lowerCase = s.toLowerCase();
        Object unmodifiableSet = null;
        if (array != null) {
            final HashSet<String> set = new HashSet<String>();
            for (int length = array.length, i = 0; i < length; ++i) {
                set.add(array[i].toLowerCase());
            }
            unmodifiableSet = Collections.unmodifiableSet((Set<?>)set);
        }
        final a a = new a(lowerCase, n, (Set<String>)unmodifiableSet);
        b.cpX.put(lowerCase, a);
        return a;
    }
    
    private static HTML$Element at(final String s, final String s2) {
        return a(s, s2, HTML$Element$Flow.cpU, 0);
    }
    
    public static HTML$Element gL(final String s) {
        return b.cpW.get(s.toLowerCase());
    }
    
    public static a gM(final String s) {
        return b.cpX.get(s.toLowerCase());
    }
}
